version: "3.9"

services:

  orchestrator:
    image: orchestrator:prod
    build:
      context: orchestrator
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATA_VOLUME: "data_upload_data"
      PGHOST: ${PGHOST}
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: ${DB_NAME}
    volumes:
      - data-upload_data:/data
      - orchestrator_config:/config
      - orchestrator_scripts:/scripts
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  data-upload_data:
    external: true
  orchestrator_config:
  orchestrator_scripts:
